print("Criador de histórias!")
print()
animal = input("Digite um animal:")
verbo = input("Digite um verbo:")
adjetivo = input("Digite um adjetivo:")
comida = input("Digite um comida:")
lugar = input("Digite um lugar:")
idade = int(input("Digite uma idade:"))
adjetivo_lugar = input("Digite um adjetivo ao lugar:")
print()
print("Era uma vez um",animal,adjetivo,"que tinha",idade,"anos. Que morava em",lugar,adjetivo_lugar+".")
print("Um dia, ele resolveu",verbo,"enquanto comia",comida+".")
